Repository IgniteUI/igniteui-theming, pull requests merged in 2022-09, with the labels that each got.

#30 feat(spacing): add pad functions to enable customizable spacing
  sass/themes/_functions.scss
  test/_themes.spec.scss
Labels: :white_check_mark: status: verified

#31 palette(material): change warn base color in material palette
  sass/color/presets/dark/_material.scss
  sass/color/presets/light/_material.scss
Labels: :x: status: awaiting-test

#29 Create README.md
  README.md
Labels: :book: documentation
