Repository IgniteUI/igniteui-theming, pull requests merged in 2022-08, with the labels that each got.

#13 typography(presets): update presets
  sass/typography/presets/_bootstrap.scss
  sass/typography/presets/_fluent.scss
  sass/typography/presets/_indigo.scss
  sass/typography/presets/_material.scss
Labels: :x: status: awaiting-test, typography

#16 docs(*): update sass documentation
  sass/color/_functions.scss
  sass/color/_mixins.scss
  sass/color/_types.scss
  sass/elevations/_functions.scss
  sass/elevations/_mixins.scss
  sass/elevations/presets/_material.scss
  sass/themes/_functions.scss
  sass/themes/_mixins.scss
  sass/typography/_functions.scss
  sass/typography/_mixins.scss
  sass/typography/_types.scss
  sass/utils/_map.scss
  sass/utils/_math.scss
  sass/utils/_meta.scss
Labels: :book: documentation, :white_check_mark: status: verified

#19 fix(color): retrieve colors using quoted strings
  sass/color/_functions.scss
  sass/color/_mixins.scss
  sass/color/_types.scss
  test/e2e/theme.scss
Labels: :white_check_mark: status: verified

#20 refactor(*): allow custom type categories
  sass/themes/_mixins.scss
  sass/typography/_mixins.scss
  test/_typography.spec.scss
Labels: :x: status: awaiting-test

#23 feat(palettes): update presets
  sass/color/presets/dark/_extra.scss
  sass/color/presets/dark/_fluent.scss
  sass/color/presets/dark/_index.scss
  sass/color/presets/light/_extra.scss
  sass/color/presets/light/_fluent.scss
  sass/color/presets/light/_index.scss
Labels: :white_check_mark: status: verified

#26 feat(animaitons): add animations
  _index.scss
  sass/_index.scss
  sass/animations/_easings.scss
  sass/animations/_index.scss
  sass/animations/_mixins.scss
  sass/animations/entrances/_bounce.scss
  sass/animations/entrances/_fade.scss
  sass/animations/entrances/_flicker.scss
  sass/animations/entrances/_flip.scss
  sass/animations/entrances/_puff.scss
  sass/animations/entrances/_roll.scss
  sass/animations/entrances/_rotate.scss
  sass/animations/entrances/_scale.scss
  sass/animations/entrances/_slide.scss
  sass/animations/entrances/_slit.scss
  sass/animations/entrances/_swing.scss
  sass/animations/entrances/_swirl.scss
  sass/animations/exits/_bounce.scss
  sass/animations/exits/_fade.scss
  sass/animations/exits/_flicker.scss
  sass/animations/exits/_flip.scss
  sass/animations/exits/_puff.scss
  sass/animations/exits/_roll.scss
  sass/animations/exits/_rotate.scss
  sass/animations/exits/_scale.scss
  sass/animations/exits/_slide.scss
  sass/animations/exits/_slit.scss
  sass/animations/exits/_swing.scss
  sass/animations/exits/_swirl.scss
  sass/animations/generic/_flip.scss
  sass/animations/generic/_rotate.scss
  sass/animations/generic/_scale.scss
  sass/animations/generic/_shadows.scss
  sass/animations/generic/_slide.scss
  sass/animations/generic/_swing.scss
  test/_animations.spec.scss
  test/_index.scss
Labels: :white_check_mark: status: verified
