Repository IgniteUI/igniteui-theming, pull requests merged in 2022-11, with the labels that each got.

#41 fix(themes): export doughnut chart theme
  package-lock.json
  sass/themes/charts/_index.scss
Labels: :white_check_mark: status: verified

#43 fix(themes): forward chart themes
  sass/themes/_index.scss
  sass/themes/charts/_category-chart-theme.scss
  sass/themes/charts/_data-chart-theme.scss
  sass/themes/charts/_doughnut-chart-theme.scss
  sass/themes/charts/_financial-chart-theme.scss
  sass/themes/charts/_funnel-chart-theme.scss
  sass/themes/charts/_gauge-theme.scss
  sass/themes/charts/_geo-map-theme.scss
  sass/themes/charts/_graph-theme.scss
  sass/themes/charts/_pie-chart-theme.scss
  sass/themes/charts/_shape-chart-theme.scss
  sass/themes/charts/_sparkline-theme.scss
  test/e2e/theme.scss
Labels: :white_check_mark: status: verified

#49 sassdoc update
  sass/bem/_index.scss
  sass/color/_functions.scss
  sass/color/_types.scss
  sass/elevations/_functions.scss
  sass/elevations/presets/_index.scss
  sass/elevations/presets/_material.scss
  sass/themes/charts/_category-chart-theme.scss
  sass/themes/charts/_data-chart-theme.scss
  sass/themes/charts/_doughnut-chart-theme.scss
  sass/themes/charts/_financial-chart-theme.scss
  sass/themes/charts/_funnel-chart-theme.scss
  sass/themes/charts/_gauge-theme.scss
  sass/themes/charts/_geo-map-theme.scss
  sass/themes/charts/_graph-theme.scss
  sass/themes/charts/_pie-chart-theme.scss
  sass/themes/charts/_shape-chart-theme.scss
  sass/themes/charts/_sparkline-theme.scss
  sass/themes/schemas/charts/dark/_category-chart.scss
  sass/themes/schemas/charts/dark/_doughnut-chart.scss
  sass/themes/schemas/charts/dark/_financial-chart.scss
  sass/themes/schemas/charts/dark/_funnel-chart.scss
  sass/themes/schemas/charts/dark/_index.scss
  sass/themes/schemas/charts/dark/_shape-chart.scss
  sass/themes/schemas/charts/dark/_sparkline.scss
  sass/themes/schemas/charts/light/_category-chart.scss
  sass/themes/schemas/charts/light/_data-chart.scss
  sass/themes/schemas/charts/light/_doughnut-chart.scss
  sass/themes/schemas/charts/light/_financial-chart.scss
  sass/themes/schemas/charts/light/_funnel-chart.scss
  sass/themes/schemas/charts/light/_gauge.scss
  sass/themes/schemas/charts/light/_geo-map.scss
  sass/themes/schemas/charts/light/_graph.scss
  sass/themes/schemas/charts/light/_index.scss
  sass/themes/schemas/charts/light/_shape-chart.scss
  sass/themes/schemas/charts/light/_sparkline.scss
  sass/typography/_types.scss
  sass/typography/charts/_index.scss
Labels: :book: documentation, :white_check_mark: status: verified, docs: sassdoc

#51 docs(palettes): add docs for palettes
  sass/color/_charts.scss
  sass/color/presets/dark/_bootstrap.scss
  sass/color/presets/dark/_extra.scss
  sass/color/presets/dark/_fluent.scss
  sass/color/presets/dark/_indigo.scss
  sass/color/presets/dark/_material.scss
  sass/color/presets/light/_bootstrap.scss
  sass/color/presets/light/_extra.scss
  sass/color/presets/light/_fluent.scss
  sass/color/presets/light/_indigo.scss
  sass/color/presets/light/_material.scss
Labels: :white_check_mark: status: verified, docs: sassdoc

#52 chore(palettes): add a little script to preview palettes
  package-lock.json
  package.json
  scripts/previewPalette.mjs
Labels: :white_check_mark: status: verified

#50 refactor(fluent): update secondary palette color
  sass/color/presets/dark/_fluent.scss
  sass/color/presets/light/_fluent.scss
Labels: :x: status: awaiting-test
